{
  "formatVersion": "1.1",
  "component": {
    "group": "Spi",
    "module": "plugin",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-1.0.4.jar",
          "url": "plugin-1.0.4.jar",
          "size": 17052,
          "sha512": "6cf2f12ca317aee6710701d988f85bd6e6105fdb6b0bf0f0e7f0b26b096f53ab0707ce716bf690e58628aa109f5a76c71145e85624bb7aa317ce690714d6724d",
          "sha256": "90242802f87cfb6556cc025f935a04d6f3060c39c27893f51fc76bb411f8f511",
          "sha1": "7d5f809bfb6bf4689ba5ed6d481f398d99cb9839",
          "md5": "f88aeb9cfad37fe9f5d26e0dddf9ccff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.lzx.spi",
          "module": "serviceloader",
          "version": {
            "requires": "0.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.4.jar",
          "url": "plugin-1.0.4.jar",
          "size": 17052,
          "sha512": "6cf2f12ca317aee6710701d988f85bd6e6105fdb6b0bf0f0e7f0b26b096f53ab0707ce716bf690e58628aa109f5a76c71145e85624bb7aa317ce690714d6724d",
          "sha256": "90242802f87cfb6556cc025f935a04d6f3060c39c27893f51fc76bb411f8f511",
          "sha1": "7d5f809bfb6bf4689ba5ed6d481f398d99cb9839",
          "md5": "f88aeb9cfad37fe9f5d26e0dddf9ccff"
        }
      ]
    }
  ]
}
